#-------------------------------
# General Site Settings

title: Naomi Krauzig

# Here you can add link in main menu
menu:
- {name: Research, url: 'work', icon: 'ion ion-ios-briefcase'}
- {name: Publications, url: 'work', icon: 'ion ion-ios-briefcase'}
- {name: Talks, url: 'work', icon: 'ion ion-ios-briefcase'}
- {name: Outreach, url: 'work', icon: 'ion ion-ios-briefcase'}
- {name: Interests, url: 'work', icon: 'ion ion-ios-briefcase'}
- {name: Blog, url: 'blog', icon: 'ion ion-ios-paper'}
- {name: CV, url: 'blog', icon: 'ion ion-ios-paper'}
- {name: Contact, url: 'contact', icon: 'ion ion-ios-mail'}

#-------------------------------
# About Section

avatar: pp.jpg
name: Naomi Krauzig
my-job: Physical Oceanographer
description: unraveling the depths of ocean data
email: naomi.krauzig@uniparthenope.it

#-------------------------------
# Skills Section

skills-title: Professional Skills
skills:
- {name: Data processing, value: '90'}
- {name: Field work, value: '85'} 
- {name: Collaboration, value: '80'}
- {name: Administration, value: '40'}
- {name: Visual Design, value: '60'}
- {name: Communication, value: '70'}
- {name: Programming, value: '90'}
- {name: Web Design, value: '55'}
- {name: Teaching, value: '35'}
- {name: Outreach, value: '70'}
- {name: Problem-solving, value: '85'}
- {name: Adaptability, value: '80'}
#-------------------------------
# Experience Section

experience-title: Experience
experience:
- {company-name: Polytechnic University of Marche & Fano Marine Center, duration: 2022 - 2024, job-position: Research Associate, description: SSD GEO12 Oceanography and Atmospheric Physics:Thermohaline variability of the Ross Sea}

- {company-name: University Parthenope of Naples, duration: 2021 - 2022, job-position: Research Associate, description: SSD GEO12 Oceanography and Atmospheric Physics:Thermohaline variability of the Ross Sea}

- {company-name: University Parthenope of Naples, duration: 2017 - 2021, job-position: Doctoral Researcher, description: Oceanographic variability of the Tyrrhenian Sea}

#-------------------------------
# Education Section

education-title: Education
education:
- {degree: Ph.D. Candidate, years: 2017 - ongoing, organization: University Parthenope of Naples, description: Dissertation: Oceanographic variability of the Tyrrhenian Sea }

- {degree: M.Sc., years: 2016 - 2017, organization: University of the Aegean, description: Thesis: Detection of thermal effluent from an aluminium plant in Antikyra Bay}

- {degree: B.Sc., years: 2012 - 2016, organization: University of the Aegean, description: Thesis: Estimation of vertical mixing in the North Aegean Sea}

#-------------------------------

#-------------------------------
# Work Section

projects:
- {
  name: Design Talks, 
  image: '10.jpg'
}
- {
  name: Abstract Page, 
  image: '11.jpg'
}
- {
  name: Round Shapes, 
  image: '12.jpg'
}
- {
  name: Color Palette,
  image: '13.jpg'
}
- {
  name: Color Palette,
  image: '14.jpg'
}
- {
  name: Color Palette,
  image: '15.jpg'
}

#-------------------------------
# Social Settings

social:
- {link: "https://www.facebook.com/naomi.krauzig/", icon: ion-logo-facebook }
- {link: "https://twitter.com/NKrauzig", icon: ion-logo-twitter }
- {link: "https://orcid.org/0000-0002-9846-4318", icon: ion-icon-information-circle }
- {link: "https://www.linkedin.com/in/naomi-krauzig-1a78b0133/", icon: ion-logo-linkedin }
- {link: "https://discord.com/users/1063529119104639057", icon: ion-logo-discord }
- {link: "https://github.com/naomikrauzig", icon: ion-logo-github }

# social network icons available (https://ionicons.com/): 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' /

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: nkrauzig # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
